name: Add App to JSON

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name'
        required: true
      download_url:
        description: 'Download URL'
        required: true

jobs:
  add-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Add App Script
        run: |
          node scripts/addAppToJson.js
        env:
          APP_NAME: ${{ github.event.inputs.app_name }}
          DOWNLOAD_URL: ${{ github.event.inputs.download_url }}
