name: Remove Last App from JSON

on:
  workflow_dispatch:
    inputs:
      json_file:
        description: 'Select JSON File'
        required: true
        default: 'TrollApps'

jobs:
  remove-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Remove Last App Script
        run: |
          node Scripts/removeLastAppFromJson.js
        env:
          JSON_FILE: ${{ github.event.inputs.json_file }}

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Repos/${{ github.event.inputs.json_file }}.json
          git commit -m "Remove last app from ${{ github.event.inputs.json_file }}.json"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
