name: Update Versions

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run Update Script
        run: |
          # Fetch latest release information using GitHub API
          REPOS=("Bootstrap" "Helium" "BHTwitter" "Winston" "Geranium")
          for APP_NAME in "${REPOS[@]}"; do
            RELEASE_INFO=$(curl -s "https://api.github.com/repos/$APP_NAME/releases/latest")
            VERSION=$(echo "$RELEASE_INFO" | jq -r ".tag_name")

            # Update the version in the JSON file
            sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" EAD.json
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
