name: Update Versions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run Update Script
        run: |
          REPOS=("Bootstrap:roothide" "Helium:leminlimez" "BHTwitter:BandarHL" "Winston:lo-cafe" "Geranium:c22dev")
          for REPO_INFO in "${REPOS[@]}"; do
            APP_NAME=$(echo $REPO_INFO | cut -d':' -f1)
            OWNER=$(echo $REPO_INFO | cut -d':' -f2)
            
            echo "Updating $APP_NAME..."
            RELEASE_INFO=$(curl -s "https://api.github.com/repos/$OWNER/$APP_NAME/releases/latest")
            
            if [ "$(echo "$RELEASE_INFO" | jq -r '.message')" == "Not Found" ]; then
              echo "No releases found for $APP_NAME."
              continue
            fi
            
            VERSION=$(echo "$RELEASE_INFO" | jq -r ".tag_name")
            sed -i "/\"name\": \"$APP_NAME\"/{N;s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/}" EAD.json
            echo "Update complete for $APP_NAME. Latest version: $VERSION"
          done

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add EAD.json
          git commit -m "Update versions [skip ci]"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
